---
vm_public_keys: ''
vm_user_data: |+
  #cloud-config
  runcmd:
    - [ userdel, --remove, ubuntu ]
    - [ rm, -rf, /home/ubuntu]
  ntp:
    enabled: true
  timezone: Etc/UTC
  disable_root: true
  users:
    - name: ansible
      gecos: Ansible User
      groups: users,admin,sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /usr/bin/bash
      lock_passwd: true
      ssh_authorized_keys:
        - "{{ ansible_user_public_key }}"
  package_update: true
  package_upgrade: true
  packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - dpkg
    - gawk
    - gnupg
    - gpg
    - grep
    - htop
    - iotop
    - nfs-common
    - nmap
    - open-iscsi
    - procps
    - python3-apt
    - software-properties-common
    - tmux
    - tzdata
    - util-linux
    - wget
    - xz-utils
  write_files:
    - path: /etc/systemd/networkd.conf
      content: |
        [Network]

        [DHCPv4]
        DUIDType=link-layer-time

        [DHCPv6]
        DUIDType=link-layer-time
      permissions: '0644'
    - path: /etc/needrestart/conf.d/disable_service_restart.conf
      content: |
        $nrconf{restart} = 'l';
      permissions: '0644'
    - path: /etc/modprobe.d/blacklist-floppy.conf
      content: |
        blacklist floppy
      permissions: '0644'
    - path: /etc/systemd/network/00-ens.network
      content: |
        [Match]
        Name=ens*

        [Network]
        DHCP=yes
        LinkLocalAddressing=ipv6
        IPv6AcceptRA=yes

        [DHCP]
        RouteMetric=100
        UseMTU=true
      permissions: '0644'
    - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      content: |
        network: {config: disabled}
      permissions: '0644'
  runcmd:
    - [ dpkg-reconfigure, initramfs-tools ]
  power_state:
    delay: "+2"
    mode: poweroff
    message: Deployment done
    timeout: 30
    condition: True
